### ISSUE TITLE
Needs more american pride

### ISSUE THREAD

**Issue by krockpot** [MrPickles/dtl#4]
i recommend https://cdn.discordapp.com/attachments/428695150294859790/774415899066761216/5TEPU2PMSNBGXDC2TA6JFVD6KQ.jpg to commemorate the accomplishments of Philadelphia in November 2020. Trigger word-cheesesteak.

**Comment by krockpot** [comment]
bump can you please triage this? we still need this feature ASAP

**Comment by MrPickles** [comment]
It might also be worth giving a 50% chance of showing the picture below from this Trump tweet: https://twitter.com/realDonaldTrump/status/1306011803374227458/photo/1

![](https://pbs.twimg.com/media/Eh_iyluWAAEGamY?format=jpg&name=large)

That way we get twice as many old men with cheesesteaks. Thoughts? @krockpot

**Comment by krockpot** [comment]
I think his chances are much lower than that @MrPickles

**Comment by MrPickles** [comment]
That's a really good point. Right now the [betting markets](https://polymarket.com/market/which-party-will-win-pennsylvania-in-the-2020-presidential-election) give Trump ~7% chance of winning PA. So we can make the bot probability match.

<img width="1031" alt="Screen Shot 2020-11-06 at 7 49 29 PM" src="https://user-images.githubusercontent.com/1161419/98427001-49fe7580-2069-11eb-9967-69b382daa69b.png">

The alternative is to give the Biden image a 69% chance of showing up in order to give him the edge while respecting the possibility that people might stop counting votes.

**Comment by MrPickles** [comment]
Actually fixed via https://github.com/MrPickles/dtl/commit/fe090c97bfd3c0cba91e885fc21b96d6d693278e
